import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Sora } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import ToastProvider from "@/components/providers/ToastProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Priorix",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} ${sora.variable} antialiased`}
      >
        <ToastProvider />
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
