### Extract text from PDF
POST http://localhost:3000/api/utils/extract-pdf
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

< ./test/data/sample.pdf
--MyBoundary--
